variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - build
    - test
    - package
    - deploy


cache:
  paths:
     - .m2/repository
     - target

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Maven compile started"
    - "mvn compile"

test_job:
  stage: test
  tags:
    - docker

  script:
    - echo "maven test started"
    - Maven test

package_job:
  stage: package
  tags:
    - docker

Deploy_job:
  stage: deploy
   tags:
    - docker

  script:
    - echo "deploy started"
    - mvn deploy
