variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - build
    - scan
    - test
    - package
    - deploy


cache:
  paths:
     - .m2/repository
     - target

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Maven compile started"
    - mvn compile

scanning_job:
  stage: scan
  image: ubuntu:latest
  #tags: 
   # - 
  script:
    - srcclr scan /opt/veracode/VeracodeJavaAPI.jar -vid $VERACODE_API_KEY_ID -vkey $VERACODE_API_KEY_SECRET --file /app/verademo.jar -action uploadandscan --allow-dirty

pipeline-scan_job:
  stage: scan
  image: veracode/pipeline-scan:latest
  tags:
    - docker
  script:
    - java -jar /opt/veracode/pipeline-scan.jar -vid $VERACODE_API_KEY_ID -vkey $VERACODE_API_KEY_SECRET --file /app/verademo.jar

test_job:
  stage: test
  tags:
    - docker

  script:
    - echo "maven test started"
    - mvn test

package_job:
  stage: package
  tags:
    - docker
  
  script:
    - echo "Maven packaging"
    - mvn package

Deploy_job:
  stage: deploy
  tags:
    - docker
  script:
    - echo "deploy started"
    - mvn deploy
